version: "3.7"
services:
    web:
        build: .
        ports:
        - "5000:5000"
        depends_on:
        - database
    database:
        container_name: risk-approvals-engine-db
        image: postgres:12.3-alpine
        volumes:
        - ./pg-init-scripts:/docker-entrypoint-initdb.d
        environment:
        - POSTGRES_USER=mahzan
        - POSTGRES_PASSWORD=Mahzan20%
        - POSTGRES_DB=mahzan
        ports:
        - "5432:5432"
